IF
  Clicked([ANYONE])
  Global("toggle","AR1513",1)
  Global("page","AR1513",5)
  Global("%Variable%","GLOBAL",%Value%)
THEN
  RESPONSE #100
    DisplayString(Myself,50658)
    IncrementGlobal("page","AR1513",1)
    GiveItemCreate("%Item%",LastTrigger,%Charge1%,%Charge2%,%Charge3%)
    GiveItemCreate("scrl8z",LastTrigger,0,0,0) // Simulacrum
    GiveItemCreate("scrl9b",LastTrigger,0,0,0) // Summon Fiend
END
