IF
  Clicked([ANYONE])
  Global("toggle","AR1513",1)
  Global("page","AR1513",5)
THEN
  RESPONSE #100
    DisplayString(Myself,50658) // The enchanted book creates several magical items for you
    IncrementGlobal("page","AR1513",1)
    GiveItemCreate("ring09",LastTrigger,0,0,0) // Ring of Free Action
    GiveItemCreate("scrl8z",LastTrigger,0,0,0) // Simulacrum
    GiveItemCreate("scrl9b",LastTrigger,0,0,0) // Summon Fiend
END
